Shippingway.seed(:id,
  { :id =>  0, :status_num => 1, :name => "未定"},
  { :id =>  1, :status_num => 1, :name => "らくらくFRIMA便"},
  { :id =>  2, :status_num => 1, :name => "アーキ"},
  { :id =>  3, :status_num => 1, :name => "アークスタンダード"},
  { :id =>  4, :status_num => 1, :name => "アークテリクス"},
  { :id =>  5, :status_num => 1, :name => "アーサスベイプ"},
  { :id =>  6, :status_num => 1, :name => "アージェントグリーム"},
  { :id =>  7, :status_num => 1, :name => "アージュヴェール"},
  { :id =>  8, :status_num => 1, :name => "アースミュージック&エコロジー"},
  { :id =>  9, :status_num => 1, :name => "アースメイド"},
  { :id => 10, :status_num => , :name => "アーツアンドクラフツ"},
  { :id => 11, :status_num => , :name => "アーツアンドサイエンス"},
  { :id => 12, :status_num => , :name => "アーティショ"},
  { :id => 13, :status_num => , :name => "アーティズ"},
  { :id => 14, :status_num => , :name => "アーテクルール"},
  { :id => 15, :status_num => , :name => "アーデム"},
  { :id => 16, :status_num => , :name => "アートヴィンテージ"},
  { :id => 17, :status_num => , :name => "アートブラウン"},
  { :id => 18, :status_num => , :name => "アーネストソーン"},
  { :id => 19, :status_num => , :name => "アーノット"}
)